config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"
  
  resources :articles do
    resources :comments
    resources :likes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :likes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end 

  private
  
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.new(user_id: current_user.id, article_id: params[:article_id])

    if @like.save
      redirect_to root_path
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy

    redirect_to root_path
  end

  private

  def find_article
    @articles = Article.find(params[:article_id])
  end
end

app/helpers/anki_helper.rb
module AnkiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<% if user_signed_in? %>
  <p>Hello <%= current_user.email %> you liked <%= current_user.likes.count %> article</p>
<% end %>
<button class="button-63 new_article" role="button">
  <%= link_to "New Article", new_article_path, class: :btn %>
</button>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Show</th>
      <th scope="col">Like count</th>
      <th scope="col">Like/Dislike</th>
      <th scope="col">Destroy</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <th scope="row"><%= article.id%></th>
        <td><%= article.title %></td>
        <td>
          <button class="button-71" rote="button" >
            <%= link_to "Show", article, :class => "btn"%>
          </button>
        </td>
        <td><%= article.likes.count %><%= (article.likes.count > 1) ? ' likes' : ' like'%></td>
        <% article_like = article.likes.where(user_id: current_user.id).first %>
        <% if article.user_id != current_user.id %>
          <% if article_like.present? %>
            <td><%= link_to article_like_path(article, article_like), method: :delete, class: 'btn-navbar' do %>
              <i class="fa fa-thumbs-up" aria-hidden="true"></i>
              <% end %>
            </td>
          <% else %>
            <td><%= link_to article_likes_path(article, article_like), method: :post, class: 'btn-navbar' do %>
              <i class="fa fa-thumbs-down" aria-hidden="true" style="color: red;"></i>
              <% end %>
              
            </td>
          <% end %>
        <% else %>
          <td></td>
        <% end %>

        <% if article.user_id != current_user.id %>
          <td></td>
        <% else %>
          <td><%= link_to article_path(article), method: :delete, class: 'btn-navbar' do %>
            <i class="fa fa-trash-o" aria-hidden="true" style="color: red;"></i>
            <% end %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
function myFunction(x) {
  x.classList.toggle("fa-thumbs-down");
}
</script>

app/views/articles/new.html.erb
<div class="new_article_page">
  <h1>New Article</h1>
  <%= render "form", article: @article %>
</div>

app/views/articles/show.html.erb
<div  class="home_button">
  <%= button_to root_path, method: :get, class: 'btn' do %>
    <i class="fa fa-home"></i> Home</button>
  <% end %>
</div>
<div class="new_article_page">
<h2><%= @article.title %></h2>

<p><%= @article.body %>
  <% if current_user == @article.user %>
    <%= link_to edit_article_path(@article), class: 'btn-navbar' do %>
      <i class="fa fa-pencil delete_edit" aria-hidden="true"></i>
    <% end %>
    <%= link_to article_path(@article), method: :delete, class: 'btn-navbar' do %>
      <i class="fa fa-trash-o" aria-hidden="true"></i>
    <% end %>
  <% end %>                
</p> 

<% if @article.comments.present? %>
  <h3>Comments</h3>
<% end %>

<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
    <li>
      <%= link_to "Destroy", article_comment_path(@article, comment), method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <p class="navbar-text float-right new_article_page"><br>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to edit_user_registration_path, :class => 'navbar-link' do %>
      <i class="fa fa-user edit_button"></i>
      <% end %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    <%= yield %><br>
    <% if user_signed_in? %>
      <p class="new_article_page"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></p>
    <% end %>
  </body>
</html>